#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : lockfile
Version  : 0.10.2
Release  : 12
URL      : http://tarballs.openstack.org/pylockfile/lockfile-0.10.2.tar.gz
Source0  : http://tarballs.openstack.org/pylockfile/lockfile-0.10.2.tar.gz
Summary  : Platform-independent file locking module
Group    : Development/Tools
License  : MIT
Requires: lockfile-python
BuildRequires : Jinja2
BuildRequires : Pygments
BuildRequires : Sphinx-python
BuildRequires : docutils-python
BuildRequires : markupsafe-python
BuildRequires : nose-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools
BuildRequires : tox
BuildRequires : virtualenv

%description
The lockfile package exports a LockFile class which provides a simple API for
locking files.  Unlike the Windows msvcrt.locking function, the fcntl.lockf
and flock functions, and the deprecated posixfile module, the API is
identical across both Unix (including Linux and Mac) and Windows platforms.
The lock mechanism relies on the atomic nature of the link (on Unix) and
mkdir (on Windows) system calls.  An implementation based on SQLite is also
provided, more as a demonstration of the possibilities it provides than as
production-quality code.

%package python
Summary: python components for the lockfile package.
Group: Default

%description python
python components for the lockfile package.


%prep
%setup -q -n lockfile-0.10.2

%build
python2 setup.py build -b py2
python3 setup.py build -b py3

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
python2 setup.py test || :
%install
rm -rf %{buildroot}
python2 setup.py build -b py2 install --root=%{buildroot}
python3 setup.py build -b py3 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
