#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : lockfile
Version  : 0.12.2
Release  : 19
URL      : http://tarballs.openstack.org/pylockfile/lockfile-0.12.2.tar.gz
Source0  : http://tarballs.openstack.org/pylockfile/lockfile-0.12.2.tar.gz
Summary  : Platform-independent file locking module
Group    : Development/Tools
License  : MIT
Requires: lockfile-python
BuildRequires : Jinja2
BuildRequires : Pygments
BuildRequires : Sphinx-python
BuildRequires : docutils-python
BuildRequires : nose-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools
BuildRequires : tox
BuildRequires : virtualenv

%description
Note: This package is **deprecated**. It is highly preferred that instead of
using this code base that instead `fasteners`_ or `oslo.concurrency`_ is
used instead. For any questions or comments or further help needed
please email `openstack-dev`_ and prefix your email subject
with ``[oslo][pylockfile]`` (for a faster response).

%package python
Summary: python components for the lockfile package.
Group: Default

%description python
python components for the lockfile package.


%prep
%setup -q -n lockfile-0.12.2

%build
python2 setup.py build -b py2
python3 setup.py build -b py3

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
PYTHONPATH=%{buildroot}/usr/lib/python2.7/site-packages python2 setup.py test || :
%install
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot}
python3 -tt setup.py build -b py3 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
